### ISSUE TITLE
Home-made ARM support not working?

### ISSUE THREAD

**Issue by roomcays** [xbrowsersync/api-docker#11]
Hi there.
Based on the included `dockerfile` I have built XBrowserSync image on my RaspberryPi 3. It seemed to build properly.
However now when I try to run it behind the Nginx proxy (so not using Traefik) I keep getting:

> 502 Bad Gateway

and Nginx logs an error:

> Nov 27 11:47:40 rpi3 nginx[258330]: 2020/11/27 11:47:40 [error] 258330#258330: *268 recv() failed (104: Unknown error) while reading response header from upstream, client: 192.168.1.1, server: xbsapi.domain.ltd, request: "GET / HTTP/2.0", upstream: "http://127.0.0.1:8082/", host: "xbsapi.domain.ltd"

I use `docker-compose.yml` as follows:

```yaml
version: "3.7"

volumes:
  xbs-db-data:
    external: true

services:
  db:
    image: "mongo:4.2.6"
    container_name: "xbs-db"
    environment:
      - "MONGO_INITDB_DATABASE=xbrowsersync"
      - "MONGO_INITDB_ROOT_PASSWORD=$XBS_DB_PASSWORD"
      - "MONGO_INITDB_ROOT_USERNAME=$XBS_DB_USERNAME"
    restart: "always"
    volumes:
      - "xbs-db-data:/data/db"
      - "./mongoconfig.js:/docker-entrypoint-initdb.d/mongoconfig.js"

  api:
    image: e6d3618beb73 # "local/xbrowsersync"
    container_name: "xbs-api"
    depends_on:
      - "db"
    environment:
      - "XBROWSERSYNC_DB_PWD=$XBS_DB_PASSWORD"
      - "XBROWSERSYNC_DB_USER=$XBS_DB_USERNAME"
    ports:
      - "8082:8080"
    restart: "always"
    volumes:
      - "./settings.json:/usr/src/api/config/settings.json"
```

The `e6d3618beb73` image hash is the reference to locally-built image for `xbrowsersync/api`, but built on ARM architecture.

Because I use Nginx on that "machine" natively (i.e. not with Docker) I have removed all *Treafik* stuff and redirected port `8080` from container to `8082` on host.
Containers (`mongodb` and `xbrowsersync/api`) start properly, they don't restart.

When trying to connect to the container bypassing the nginx, i.e. from within the host, I get "*Connection reset by peer*" error:

```
$ curl -vvv http://localhost:8082
*   Trying ::1:8082...
* Connected to localhost (::1) port 8082 (#0)
> GET / HTTP/1.1
> Host: localhost:8082
> User-Agent: curl/7.73.0
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

However **absolutely nothing** is getting written to container logs, like there have been no requests at all. The last thing that gets logged is:

> xbs-api | Provisioner finished.

I keep wondering where might be the cause of that unavailability. I doubt it is Nginx. Might it be the reason that image is not available for ARM officaly at hub.docker.com?

Is there anyone there who can help me? I'd love to self-host that solution on my low-energy RPI3 at home... :)

**Comment by nero120** [comment]
Hi @roomcays, I also run an RP3 at home (running Nextcloud) so would be keen to get XBS running on it but didn't have the time to try yet so am interested in this.

Unfortunately I have very little spare time at the moment, I'm desperately trying to finish and deploy the next app release (v1.6.0) so the little spare time I have is going there. Once that's out, my next to-do item is to update the API so can look into this then, but I have no estimate for when that will be currently, sorry.

**Comment by roomcays** [comment]
@nero120 I am willing to help if you'd need my assistance. I code in PHP, but I do Docker a lot for daily work (development environments setup). So I can test new releases :)

**Comment by elbosso** [comment]
Hi, i have added a Dockerfile and a docker-compose.yml file for reference - although please note: I do not run this on a raspi but I use a rockpi instead, which means: arm64. 

With the files provided, it runs smoothly with Traefik 2.x:

```
FROM arm64v8/node

# Set environment variables
ENV XBROWSERSYNC_API_VERSION 1.1.12

WORKDIR /usr/src/api

# Download release and unpack
RUN wget -q -O release.tar.gz https://github.com/xBrowserSync/api/archive/v$XBROWSERSYNC_API_VERSION.tar.gz \
        && tar -C . -xzf release.tar.gz \
        && rm release.tar.gz \
        && mv api-$XBROWSERSYNC_API_VERSION/* . \
        && rm -rf api-$XBROWSERSYNC_API_VERSION/

# Install dependencies
RUN npm install --only=production

# Expose port and start api
EXPOSE 8080
CMD [ "node", "dist/api.js"]
```

```
version: '3.3'

services:
  xbs-db:
    container_name: "xbs-db"
    environment:
      - "MONGO_INITDB_DATABASE=xbrowsersync"
      - "MONGO_INITDB_ROOT_PASSWORD=changeme"
      - "MONGO_INITDB_ROOT_USERNAME=xbs-root"
    image: "mongo:4.2.6"
    restart: "unless-stopped"
    volumes:
      - "./xbs-db-data:/data/db"
      - "./mongoconfig.js:/docker-entrypoint-initdb.d/mongoconfig.js"
    networks:
      - default
  xbs-api:
    build:
      context: ./ # Local
      dockerfile: Dockerfile_arm64
    container_name: "xbs-api"
    depends_on:
      - "xbs-db"
    environment:
      - "XBROWSERSYNC_DB_PWD=chanheme"
      - "XBROWSERSYNC_DB_USER=xbs-root"
#    image: "xbrowsersync/api:1.1.12"
#    ports:
#      - "8080:8080"
    restart: "unless-stopped"
    volumes:
      - "./settings.json:/usr/src/api/config/settings.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.xbrowsersync.rule=Host(`xbrowsersync.pi-docker.lab`)"
      - "traefik.http.services.xbrowsersync.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_proxy"
    networks:
      - traefik_proxy
      - default

networks:
  traefik_proxy:
    external:
      name: pi_traefik_proxy
  default:
    driver:
      bridge
```
