### ISSUE TITLE
Standalone API image

### ISSUE THREAD

**Issue by viharm** [xbrowsersync/api-docker#7]
Hi, I am trying to use a standalone API image as I am trying to deploye *xBrowserSync* behind an existing *nginx* installation.

I have a container running *MongoDB* listening on the host's interface at the default port (`27017`). I can confirm this running as I can connect to this *MongoDB* instance from a different physical host on my local network.

Unfortunately, the standalone *xBrowserSync* image (`xbrowsersync`/`api`:`latest`) seems to crash repeatedly. I have followed instructions from https://github.com/xbrowsersync/api-docker#running-the-api-image and using some of the options from https://github.com/xbrowsersync/api#4-modify-configuration-settings.

I can't seem to get to view the logs, and I cannot login to the container, as it crashes repeatedly.

Please could you help me with how I can debug it?

(It doesn't help that I am fairly new to both *Docker* and *MongoDB*).

**Comment by nero120** [comment]
If you are already running MongoDB then it's likely conflicting with the MongoDB container in the docker-compose file, likely a port conflict. Stop all existing containers and then try again.

**Comment by viharm** [comment]
> 
> 
> If you are already running MongoDB then it's likely conflicting with the MongoDB container in the docker-compose file, likely a port conflict. Stop all existing containers and then try again.

@nero120 , thanks for your response. I am not running the API from the docker-compose file. I am running a container directly from the API image; so I presume that a second instance is not running.

**Comment by nero120** [comment]
Ok what do you see if you run:

```
docker logs [api_container_name]
```

(replace `[api_container_name]` with the name of the xBrowserSync API container )

**Comment by viharm** [comment]
@nero120 , I will retry and provide feedback by next week.

**Comment by viharm** [comment]
@nero120 , unfortunately I was unable to re-trace my steps to get the _Mongo_ instance setup and subsequently with the _xBrowserSync_ API image. I have given up on reusing an existing _Mongo_ instance and used the composer file. I removed the _traefik_ section of the _docker-compose_ file, but had to move the _ports_ declarations from _traefik_ to _api_ sections.

**Comment by nero120** [comment]
Ok thanks for the update @viharm, glad that you're up and running now in any case.

**Comment by lonix1** [comment]
Does someone have an example to share (docker-compose.yml) of how to get it working without traefik?

**Comment by viharm** [comment]
I ended up using the exclusive _MongoDB_ image configured for use with the API image. However I wanted to control the public-facing side, so put it behind an _nginx_ instance.

Here's my docker compose file to use without _traefik_

```yml
version: "3.7"

volumes:
  xbs-db-data:

services:
  db:
    container_name: "xbs-db"
    environment:
      - "MONGO_INITDB_DATABASE=xbrowsersync"
      - "MONGO_INITDB_ROOT_PASSWORD=$XBS_DB_PASSWORD"
      - "MONGO_INITDB_ROOT_USERNAME=$XBS_DB_USERNAME"
    image: "mongo:4.2.0"
    labels:
      - "traefik.enable=false"
    networks:
      - "xbs-net"
    restart: "always"
    volumes:
      - "xbs-db-data:/data/db"
      - "./mongoconfig.js:/docker-entrypoint-initdb.d/mongoconfig.js"
  api:
    container_name: "xbs-api"
    depends_on:
      - "db"
    environment:
      - "XBROWSERSYNC_DB_PWD=$XBS_DB_PASSWORD"
      - "XBROWSERSYNC_DB_USER=$XBS_DB_USERNAME"
    image: "xbrowsersync/api:1.1.10"
    labels:
      - "traefik.frontend.rule=Host:$XBS_API_HOSTNAME"
      - "traefik.port=8080"
    networks:
      - "xbs-net"
    ports:
      - "8080:8080"
    restart: "always"
    volumes:
      - "./settings.json:/usr/src/api/config/settings.json"

networks:
  xbs-net:
```
